version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/stone-paper-scissors
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend

volumes:
  mongo_data:
